name: 'Upload multi files to GitHub release assets'
description: 'Upload file to GitHub release assets'
inputs:
  tag:
    description: 'git tag'
    required: true
    default: ${{ github.ref }}
  asset-path:
    description: 'file path to be uploaded'
    required: true
    default: ''
  gh_token:
    description: 'gh_token from import'
    required: false
    default: ''
  release_id:
    description: 'release id'
    required: true
    default: ''
  
runs:
  using: "composite"
  steps:
    - name: upload
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [ ${{ inputs.gh_token }} == '' ]; then
          echo "gh_token from input is null, read from env"
        else
          echo "get gh_token success"
          export GH_TOKEN=${{ inputs.gh_token }}
        fi
        j=0
        if [ -d ${{ inputs.asset-path }} ]; then
            for filename in `ls ${{ inputs.asset-path }}`;
            do
                folder_list[j]=${{ inputs.asset-path }}/$filename
                j=`expr $j + 1`
            done
        else
            folder_list[0]=${{ inputs.asset-path }}
        fi
        echo "Uploading asset... "
        for filepath in ${folder_list[@]};
        do
            filename=$(basename "${filepath}")
 
            gh release upload ${{ inputs.tag }} ${filepath}) --clobber --repo ${{ github.repository }}
              /repos/OWNER/REPO/releases/${{ inputs.release_id }}/assets?name=${filepath}
 
        done
      shell: bash
