name: 'Upload multi files to GitHub release assets'
description: 'Upload file to GitHub release assets'
inputs:
  tag:
    description: 'git tag'
    required: true
    default: ${{ github.ref }}
  asset-path:
    description: 'file path to be uploaded'
    required: true
    default: ''
  gh_token:
    description: 'gh_token from import'
    required: false
    default: ''
 
  
runs:
  using: "composite"
  steps:
    - name: upload
      run: |
        if [ -z ${{ inputs.gh_token }} ]; then
          echo "gh_token from input is null, read from env"
        else
          echo "get gh_token success"
          export GH_TOKEN=${{ inputs.gh_token }}
        fi
        j=0
        if [ -d ${{ inputs.asset-path }} ]; then
            for filename in `ls ${{ inputs.asset-path }}`;
            do
                folder_list[j]=$filename
                j=`expr $j + 1`
            done
        else
            folder_list[0]=${{ inputs.asset-path }}
        fi
        echo "Uploading asset... "
        cd ${{ inputs.asset-path }}
        for filepath in ${folder_list[@]};
        do
            filename=$(basename "${filepath}")
            echo "filename $filename"
            echo "filepath ${filepath}"

           
            gh release upload ${{ inputs.tag }} $filename --clobber --repo ${{ github.repository }} 
        done
      shell: bash
